version: 2
jobs:
  bootstrap-build:
    docker:
      - image: codesmithy/gcc-bootstrap-build-prerequisites:0.11.0
    steps:
      - run: 
          name: "Set CODESMITHYIDE_ROOT environment variables"
          command: echo 'export CODESMITHYIDE_ROOT="/workspace/projects/codesmithyide"' >> $BASH_ENV
      - checkout:
          path: /workspace/projects/codesmithyide/package-toolchains
      - run:
          name: Build
          command: cd /workspace/projects/codesmithyide/package-toolchains/build-files/gnumake && make
      - run:
          name: Test build
          command: cd /workspace/projects/codesmithyide/package-toolchains/tests/build-files/gnumake && make
      - run:
          name: Run the tests
          command: cd /workspace/projects/codesmithyide/package-toolchains/tests/build-files/gnumake && ./CodeSmithyPackageToolchainsTests --persistent-storage=/build/test-output --junit-xml-test-report=/build/test-results/CodeSmithyPackageToolchains.xml
      - store_artifacts:
          name: Upload test output files
          path: /build/test-output
          destination: test-output
      - store_artifacts:
          name: Upload test report files
          path: /build/test-results/CodeSmithyPackageToolchains.xml
          destination: CodeSmithyPackageToolchains-test-results.xml
      - store_test_results:
          name: Upload test results to CircleCI
          path: /build/test-results/CodeSmithyPackageToolchains.xml

  build:
    docker:
      - image: codesmithy/gcc-build-prerequisites:0.14.0
    steps:
      - run:
          name: "Set CODESMITHYIDE_ROOT environment variables"
          command: echo 'export CODESMITHYIDE_ROOT="/workspace/projects//codesmithyide"' >> $BASH_ENV
      - checkout:
          path: /workspace/projects/codesmithyide/package-toolchains
      - run:
          name: Build
          command: cd /workspace/projects/codesmithyide/package-toolchains/build-files/gnumake && make
      - run:
          name: Test build
          command: cd /workspace/projects/codesmithyide/package-toolchains/tests/build-files/gnumake && make
      - run:
          name: Run the tests
          command: cd /workspace/projects/codesmithyide/package-toolchains/tests/build-files/gnumake && ./CodeSmithyPackageToolchainsTests --persistent-storage=/build/test-output --junit-xml-test-report=/build/test-results/CodeSmithyPackageToolchains.xml
      - store_artifacts:
          name: Upload test output files
          path: /build/test-output
          destination: test-output
      - store_artifacts:
          name: Upload test report files
          path: /build/test-results/CodeSmithyPackageToolchains.xml
          destination: CodeSmithyPackageToolchains-test-results.xml
      - store_test_results:
          name: Upload test results to CircleCI
          path: /build/test-results/CodeSmithyPackageToolchains.xml
workflows:
  version: 2
  continuous_build:
    jobs:
      - bootstrap-build
      - build
  weekly_build:
    jobs:
      - bootstrap-build
      - build
    triggers:
      - schedule:
          cron: "0 8 * * 0"
          filters:
            branches:
              only:
                 - main
